///////////////////////////////////////////////////////////////////////////////
// PMJ_Driver_ProjectServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_PMJ_Driver_Project = 0x3F000000;
#define SRVNAME_PMJ_DRIVER_PROJECT "PMJ_Driver_Project"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_PMJ_Driver_ProjectCpmjTransform = {0x23cc5dde,0x92f1,0x4217,{0x9d,0x78,0xac,0x68,0x54,0x93,0x43,0x7d}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_pmjTransformLength = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
#if !defined(_TC_IID_05010001_0000_0000_E000_000000000064_INCLUDED_)
#define _TC_IID_05010001_0000_0000_E000_000000000064_INCLUDED_
TCOM_DECL_INTERFACE("05010001-0000-0000-e000-000000000064", ITcNcTrafo)
#endif // !defined(_TC_IID_05010001_0000_0000_E000_000000000064_INCLUDED_)

///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
