///////////////////////////////////////////////////////////////////////////////
// PMJ_Driver_ProjectClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "PMJ_Driver_ProjectClassFactory.h"
#include "PMJ_Driver_ProjectServices.h"
#include "PMJ_Driver_ProjectVersion.h"
#include "pmjTransform.h"

BEGIN_CLASS_MAP(CPMJ_Driver_ProjectClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_PMJ_Driver_ProjectCpmjTransform, SRVNAME_PMJ_DRIVER_PROJECT "!CpmjTransform", CpmjTransform)
///</AutoGeneratedContent>
END_CLASS_MAP()

CPMJ_Driver_ProjectClassFactory::CPMJ_Driver_ProjectClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_PMJ_DRIVER_PROJECT));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(PMJ_Driver_Project));
#endif //defined(TCDBG_UNIT_VERSION)
}

