///////////////////////////////////////////////////////////////////////////////
// pmjTransform.cpp
#include "TcPch.h"
#pragma hdrstop

#include "pmjTransform.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif
DEFINE_THIS_FILE()

///////////////////////////////////////////////////////////////////////////////
// Collection of interfaces implemented by module CpmjTransform
BEGIN_INTERFACE_MAP(CpmjTransform)
	INTERFACE_ENTRY_ITCOMOBJECT()
	INTERFACE_ENTRY(IID_ITcADI, ITcADI)
	INTERFACE_ENTRY(IID_ITcWatchSource, ITcWatchSource)
///<AutoGeneratedContent id="InterfaceMap">
	INTERFACE_ENTRY(IID_ITcNcTrafo, ITcNcTrafo)
///</AutoGeneratedContent>
END_INTERFACE_MAP()


IMPLEMENT_ITCOMOBJECT(CpmjTransform)
IMPLEMENT_ITCOMOBJECT_SETSTATE_LOCKOP2(CpmjTransform)
IMPLEMENT_ITCADI(CpmjTransform)
IMPLEMENT_ITCWATCHSOURCE(CpmjTransform)

///////////////////////////////////////////////////////////////////////////////
// Set parameters of CpmjTransform 
BEGIN_SETOBJPARA_MAP(CpmjTransform)
	SETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="SetObjectParameterMap">
	SETOBJPARA_VALUE(PID_pmjTransformLength, m_Length)
///</AutoGeneratedContent>
END_SETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get parameters of CpmjTransform 
BEGIN_GETOBJPARA_MAP(CpmjTransform)
	GETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="GetObjectParameterMap">
	GETOBJPARA_VALUE(PID_pmjTransformLength, m_Length)
///</AutoGeneratedContent>
END_GETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get watch entries of CpmjTransform
BEGIN_OBJPARAWATCH_MAP(CpmjTransform)
	OBJPARAWATCH_DATAAREA_MAP()
///<AutoGeneratedContent id="ObjectParameterWatchMap">
///</AutoGeneratedContent>
END_OBJPARAWATCH_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get data area members of CpmjTransform
BEGIN_OBJDATAAREA_MAP(CpmjTransform)
///<AutoGeneratedContent id="ObjectDataAreaMap">
///</AutoGeneratedContent>
END_OBJDATAAREA_MAP()


///////////////////////////////////////////////////////////////////////////////
// Constructor
CpmjTransform::CpmjTransform()
{
///<AutoGeneratedContent id="MemberInitialization">
	m_Length = 0;
///</AutoGeneratedContent>
}

///////////////////////////////////////////////////////////////////////////////
// Destructor
CpmjTransform::~CpmjTransform() 
{
}

///////////////////////////////////////////////////////////////////////////////
// State Transitions 
///////////////////////////////////////////////////////////////////////////////
IMPLEMENT_ITCOMOBJECT_SETOBJSTATE_IP_PI(CpmjTransform)

///////////////////////////////////////////////////////////////////////////////
// State transition from PREOP to SAFEOP
//
// Initialize input parameters 
// Allocate memory
HRESULT CpmjTransform::SetObjStatePS(PTComInitDataHdr pInitData)
{
	HRESULT hr = S_OK;
	IMPLEMENT_ITCOMOBJECT_EVALUATE_INITDATA(pInitData);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to OP
//
// Register with other TwinCAT objects
HRESULT CpmjTransform::SetObjStateSO()
{
	HRESULT hr = S_OK;
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from OP to SAFEOP
HRESULT CpmjTransform::SetObjStateOS()
{
	HRESULT hr = S_OK;
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to PREOP
HRESULT CpmjTransform::SetObjStateSP()
{
	HRESULT hr = S_OK;
	return hr;
}

///<AutoGeneratedContent id="ImplementationOf_ITcNcTrafo">
HRESULT CpmjTransform::Forward(TcNcTrafoParameter* p)
{
	HRESULT hr = E_NOTIMPL;
	return hr;
}

HRESULT CpmjTransform::Backward(TcNcTrafoParameter* p)
{
	HRESULT hr = E_NOTIMPL;
	return hr;
}

HRESULT CpmjTransform::TrafoSupported(TcNcTrafoParameter* p, bool fwd)
{
	HRESULT hr = E_NOTIMPL;
	return hr;
}

HRESULT CpmjTransform::GetDimensions(ULONG* pFwdInput, ULONG* pFwdOutput)
{
	HRESULT hr = E_NOTIMPL;
	return hr;
}
///</AutoGeneratedContent>
