<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="POU_TempControl" Id="{06724fef-7179-4225-9eab-b990c6f641a1}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM POU_TempControl
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[GVL_IO.lrExtruderTemp := GVL_IO.lrRawTemp/10.0;]]></ST>
    </Implementation>
    <LineIds Name="POU_TempControl">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>