///////////////////////////////////////////////////////////////////////////////
// pmjTransformation.h
#pragma once

#include "Untitled2Interfaces.h"

class CpmjTransformation 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST(CID_Untitled2CpmjTransformation)
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CpmjTransformation();
	virtual	~CpmjTransformation();

///<AutoGeneratedContent id="InterfaceMembers">
///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

///<AutoGeneratedContent id="Members">
///</AutoGeneratedContent>
};
