///////////////////////////////////////////////////////////////////////////////
// Untitled2Services.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_Untitled2 = 0x3F000000;
#define SRVNAME_UNTITLED2 "Untitled2"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_Untitled2CpmjTransformation = {0xacfeed50,0x953c,0x478d,{0xbb,0xa8,0x79,0xc1,0xaf,0xf4,0xd3,0xb0}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
